### ISSUE TITLE
Unable to configure DAC

### ISSUE THREAD

**Issue by jalcok1** [marionette-daq/marionette-firmware#7]
When attempting to config DAC in fetch I keep getting "unable to allocate dac pins" error. Below is a print out of my entries in fetch.  Maybe I'm using incorrect syntax.  If that's the case we need to update the wiki to show how to properly configure/use the peripheral. 

m > dac.config(1)
BEGIN:
E:unable to allocate dac pins
END:ERROR
m > dac.config(0)
BEGIN:
E:Enter a number from 1 -5
END:ERROR
m > dac.config(1)
BEGIN:
E:unable to allocate dac pins
END:ERROR
m > dac.config(2)
BEGIN:
E:unable to allocate dac pins

**Comment by SethMWard** [comment]
Code for the internal dac was referencing both channels. SS pin for the external dac was not configurable for IO_GPIO. Edited fetch_dac.c and and io_manage_defs.h respectively. Issue resolved.

**Comment by SethMWard** [comment]
Issue was with a conditional statement referencing both onboard internal
dacs, fixed in fetch_dac.c. SS pin for SPI was not configurable as a GPIO,
fixed in io_managed_defs.h. Will review io_manage_defs to make sure
everything is configured correctly and test all fetch functionality this
afternoon.
